"""
app/schemas/complaint.py — Request/response schemas for the complaint portal.

Used by:
  - Citizen portal (submit, track, reopen)
  - Officer dashboard (list, detail)
  - Public heatmap endpoint
"""

from datetime import datetime
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field


# ── Citizen: Submit a complaint ───────────────────────────────────────────────
class ComplaintCreate(BaseModel):
    """Body for POST /complaints/ — citizen submits a new pothole report."""
    description: Optional[str] = Field(None, max_length=1000)
    gps_lat: float = Field(..., ge=-90.0, le=90.0)
    gps_lng: float = Field(..., ge=-180.0, le=180.0)
    address_text: Optional[str] = Field(None, max_length=500)
    heading: Optional[float] = Field(None, ge=0.0, lt=360.0)   # compass degrees
    tilt: Optional[float] = Field(None, ge=-90.0, le=90.0)     # phone pitch


# ── One entry in the public status timeline ───────────────────────────────────
class TimelineEvent(BaseModel):
    """A single event in a complaint's lifecycle timeline."""
    action: str
    timestamp: datetime
    notes: Optional[str] = None


# ── Complaint detail response ─────────────────────────────────────────────────
class ComplaintResponse(BaseModel):
    """Full complaint data returned to citizen and officer."""
    id: UUID
    status: str
    description: Optional[str]
    gps_lat: float
    gps_lng: float
    address_text: Optional[str]
    heading: Optional[float]
    tilt: Optional[float]
    severity_score: Optional[float]
    before_photo_url: Optional[str]  # Pre-signed URL (generated by service)
    created_at: datetime
    updated_at: datetime
    timeline: list[TimelineEvent] = []

    model_config = {"from_attributes": True}


# ── Complaint list item (lighter, for list views) ────────────────────────────
class ComplaintSummary(BaseModel):
    id: UUID
    status: str
    address_text: Optional[str]
    severity_score: Optional[float]
    created_at: datetime

    model_config = {"from_attributes": True}


# ── Public heatmap GeoJSON feature ────────────────────────────────────────────
class HeatmapPoint(BaseModel):
    """One point in the public heatmap GeoJSON response."""
    lat: float
    lng: float
    status: str
    severity: Optional[float]


class HeatmapResponse(BaseModel):
    type: str = "FeatureCollection"
    points: list[HeatmapPoint]


# ── Citizen reopen request ────────────────────────────────────────────────────
class ReopenRequest(BaseModel):
    """Body for POST /complaints/{id}/reopen"""
    reason: str = Field(..., min_length=10, max_length=500)
